name: Access HEROKUAPP
on:
  push:    
  schedule:
    - cron: '*/1 * * * *'

jobs:
  job1:
    name: Access HEROKUAPP_lfproxz
    runs-on: ubuntu-latest
    steps:
      - name: Access Herokuapp_lfproxz
        run: curl https://lfproxz.herokuapp.com/
