name: Access HerokuApp
on:
  push:    
  schedule:
    - cron: '*/1 * * * *'

jobs:
  lfproxz:
    runs-on: ubuntu-latest
    steps:
      - name: Access lfproxz
        run: curl https://lfproxz.herokuapp.com/
