name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '*/1 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Weather'
        run: echo hello github
