name: Access HerokuApp
on:
  push:    
  schedule:
    - cron: '*/24 * * * *'

jobs:
  lfproxz:
    runs-on: ubuntu-latest
    steps:
      - name: Access lfproxz
        run: curl https://lfproxz.herokuapp.com/
  onepiecelf:
    runs-on: ubuntu-latest
    steps:
      - name: Access onepiecelf
        run: curl https://onepiecelf.herokuapp.com
