name: Webhook

on:
    repository_dispatch:
        types:
            - hello

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo Hello World!
